### PR TITLE
Remove inset inside CEVRK1TextView

### PR DESCRIPTION
**Pull request by eschramm**
Fixes https://github.com/CareEvolution/RKStudio-Participant/issues/841.

|Before|After|
|---|---|
|before|after|

### CODE REVIEW

**Review by mmertsock — APPROVED** [review]
LGTM

**Comment by overcyn** [comment]
Previously we have aligned the Title with text choices and the continue button. https://github.com/CareEvolution/RKStudio-Participant/issues/739

**Comment by chrisnowak** [comment]
Yes @overcyn is right - we want to maintain that so everything on the screen is consistently indented...

**Comment by eschramm** [comment]
Good point - I got out the pixel editor and have now ensured all items on a FormStep left-align. The **Text Choice** line, it appears to slice thru the anti-aliasing, so if I bump it another half-point, I think it's almost perfect (bottom)
image

Here's after increasing the margin another 0.5 points.
image

And here's an InstructionStep to see how it affects other steps.
image

**Pull request merged**
