### PR TITLE
Allow ORKWaitStep to update title/text via Notification

### PR DESCRIPTION
**Pull request by eschramm**
This allows update of the title and text of an `ORKWaitStep` via Notification.

### CODE REVIEW

**Comment by mmertsock** [comment]
Why a notification instead of just exposing `updateTitle:` in the .h file (and thus following the same approach as `updateText:`)? A notification causes all existing ORKWaitStepViewController instances to update their title to the same value

**Comment by eschramm** [comment]
Yeah, perhaps the notification could pass the stepIdentifier as an object? I was struggling at finding an elegant way to drill into the `ORK1StepViewController` from various places in the code flow where we might want to update this. I can look at the flow in MyDataHelps again and see if there's a way to drill into the step or store a reference at creation and readdress.

**Comment by chrisnowak** [comment]
Curious what htis is for?

**Comment by eschramm** [comment]
There's a loading step (ORK1WaitStep) that shows at the beginning of a StartSurvey/Task action that shows when we're downloading the survey JSON. Then when it's received, a new TaskVC is presented over that loading task. At completion/cancel, as the animation of dismissed views occurs, the Loading step reappears for a split second which looks a little strange. It came up during [AoU onboarding](https://github.com/CareEvolution/RKStudio-Participant/pull/569). This approach allows us to at least change the text from "Loading" so when it briefly reappears it seems more relevant. Also of note is that post task actions and their processing also occur during this stage at dismissal so we cannot simply remove it from the stack without some significant redesign. The reason this is being proposed now is that it shows during the dismissal for @greinard 's WebVisualizations.

**Comment by chrisnowak** [comment]
I think "Loading" is just fine tbh...I would just leave it "Loading" for now

**Pull request closed without merging**
