### PR TITLE
Add footnote to question steps and footnoteTextStyle to theme

### PR DESCRIPTION
**Pull request by mmertsock**
For https://github.com/CareEvolution/CEVResearchKit/issues/236

Note that ORK[1]FormStep, ORK[1]InstructionStep, and ORK[1]VideoInstructionStep already support footnotes.

### CODE REVIEW

**Comment by eschramm** [comment]
I noticed that `footnoteAlignment` doesn't work. I don't know how usable adjusting the alignment of the footnote would be? It looks like we'd need to mess with the constraints in `ORK[1]NavigationContainerView` which doesn't sound like fun. I'm guessing we'd need to remove the footnoteLabel from [this code](https://github.com/CareEvolution/ResearchKit/blob/27dc1770f434a9b22ee22947ca9cbcf3b69bd1be/ORK1Kit/ORK1Kit/Common/ORK1NavigationContainerView.m#L304-L326) which sets them all to be centered and pin the leading and trailing to the ends. Otherwise everything else looks good.

**Comment by mmertsock** [comment]
Good catch. I pushed a fix, it turned out to be pretty simple.

**Comment by eschramm** [comment]
LGTM 🚢

**Comment by mmertsock** [comment]
Sample JSON for testing: https://github.com/CareEvolution/CEVAndroid-Research/blob/master/cev-android-research-prototyper/src/main/assets/Definitions/StyleSampler.json and https://github.com/CareEvolution/CEVAndroid-Research/blob/master/cev-android-research-prototyper/src/main/assets/Definitions/TextStyles.json

**Pull request merged**
