### PR TITLE
Update deployment target to iOS 14

### PR DESCRIPTION
**Pull request by mmertsock**
## Testing

See main PR.

### CODE REVIEW

**Comment by mmertsock** [comment]
Noticing a unit test that is failing in CI somewhat frequently:

```
ORKStroopStepTests
  testSometimesAlignmentRandomization,
((fabs([self realTruesRandomizationTrialForStroopViewController:stroopVC] - probability.doubleValue))
less than (0.01)) failed: ("0.0122") is not less than ("0.01")
  /Users/runner/work/ResearchKit/ResearchKit/ResearchKitTests/ORKStroopStepTests.m:56

        ORKStroopStepViewController *stroopVC = [[ORKStroopStepViewController alloc] initWithStep:stroopStep];
        XCTAssertLessThan(fabs([self realTruesRandomizationTrialForStroopViewController:stroopVC] - probability.doubleValue), 0.01);
    }
```

The unit test produces 10,000 boolean values using a uniform-distribution RNG and expects 25% of the booleans to be true, plus or minus 1% (and also runs the same test with 50% and 75% probabilities). The test tends to fail by going just beyond that threshold: off by 1.22% in this case, and 1.28% in the last failed run.

(Some detail about the RNG usage may affect the uniformness of the results: it's calling `arc4random_uniform(1000)`, i.e. producing a random integer in the range `[0, 1000)` and then checking if that's below 250 in the case of the 25%-probability test.)

Seems plausible to me that this is a reasonable amount of deviation for the RNG, especially with the range of 1000 it's using from the underlying random integer?

**Comment by mmertsock** [comment]
Wrote some similar code in a Swift Playground to experiment with the `arc4random_uniform` function:

https://gist.github.com/mmertsock/d00fd6ac0e4a06ecdc9f106078315001

Most of the time, the number of true values over 10k iterations is within the expected 1% variation, but occasionally (around 1/20 runs) it will exceed the variation slightly, as we've seen in the failed CI unit tests. The `1000` upper bound used in the call to `arc4random_uniform` doesn't seem to be a significant factor in the behavior (I tested 100 and 10,000 for comparison).

I'm not sufficiently well-versed in statistics and PRNGs to know conclusively whether this is to be expected, but it feels ok to me.

**Comment by eschramm** [comment]
That is an interesting observation. I agree that 1% is arbitrary and probably too strict. I'd be game to loosen it up some to scale back false positives. Maybe like 1.5% or 2%? The impetus for the test was that I had seen situations where in Beacon we were spinning random numbers and they weren't random at all (we weren't seeding them properly) and I just wanted to have a test to verify that we are actually getting pseudorandom numbers, or at least better than something that is clearly NOT random.

**Comment by mmertsock** [comment]
> Maybe like 1.5% or 2%

That sounds fine to me: over a few hundred tests of 10k iterations each, I don't think I ever saw the difference go beyond 1.5%. I'll commit that change as part of this PR.

And the RNG code itself looks correct to me.

**Review by eschramm — APPROVED** [review]
LGTM - thanks for improving the unit test

**Pull request merged**
